<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Subscribe_footer_footerLinkHeading__2dW1j</name>
   <tag></tag>
   <elementGuidId>b3f0f217-cd27-4697-971d-5c6f53a1d687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.footer_footerLinkHeading__2dW1j</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_footerLinkHeading__2dW1j</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/hicolumn-logo-black.48e1e5c4.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;footer_footerContainer__e1Gnh&quot;]/div[@class=&quot;footer_footerLinks__3YIOx&quot;]/div[@class=&quot;footer_footerLinkWrapper__1GNCH&quot;]/div[@class=&quot;footer_footerLinkItems__1AO3M&quot;]/img[@class=&quot;footer_footerLinkHeading__2dW1j&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
